-- DataCell: PostgreSQL 17 / Supabase
-- Esquema privado para una aplicacion MVC que accede mediante una conexion de backend.

create schema if not exists datacell;
revoke all on schema datacell from public, anon, authenticated;
alter default privileges in schema datacell revoke all on tables from anon, authenticated;
alter default privileges in schema datacell revoke all on sequences from anon, authenticated;

create table datacell.roles (
    id_rol integer generated by default as identity primary key,
    nombre varchar(50) not null unique,
    constraint ck_roles_nombre check (nombre in ('ADMINISTRADOR', 'CAJERO', 'ALMACEN', 'ASISTENTE_COMPRAS'))
);

create table datacell.usuarios (
    id_usuario integer generated by default as identity primary key,
    nombres varchar(80) not null,
    apellidos varchar(80) not null,
    correo varchar(120) not null unique,
    password_hash varchar(500) not null,
    estado varchar(20) not null default 'ACTIVO',
    fecha_registro timestamptz not null default now(),
    id_rol integer not null references datacell.roles(id_rol) on delete restrict,
    constraint ck_usuarios_estado check (estado in ('ACTIVO', 'INACTIVO'))
);

create table datacell.clientes (
    id_cliente integer generated by default as identity primary key,
    nombres varchar(80) not null,
    apellidos varchar(80),
    documento varchar(20) unique,
    direccion varchar(150),
    telefono varchar(20),
    correo varchar(120) unique,
    estado varchar(20) not null default 'ACTIVO',
    fecha_registro timestamptz not null default now(),
    constraint ck_clientes_estado check (estado in ('ACTIVO', 'INACTIVO'))
);

create table datacell.proveedores (
    id_proveedor integer generated by default as identity primary key,
    ruc varchar(11) not null unique,
    razon_social varchar(150) not null,
    direccion varchar(150),
    contacto varchar(100),
    telefono varchar(20),
    correo varchar(120) unique,
    estado varchar(20) not null default 'ACTIVO',
    constraint ck_proveedores_estado check (estado in ('ACTIVO', 'INACTIVO'))
);

create table datacell.categorias (
    id_categoria integer generated by default as identity primary key,
    nombre varchar(80) not null unique
);

create table datacell.marcas (
    id_marca integer generated by default as identity primary key,
    nombre varchar(80) not null unique
);

create table datacell.productos (
    id_producto integer generated by default as identity primary key,
    codigo varchar(30) not null unique,
    codigo_barras varchar(50) unique,
    nombre varchar(120) not null,
    descripcion varchar(250),
    precio_compra numeric(12, 2) not null,
    precio_venta numeric(12, 2) not null,
    stock integer not null default 0,
    stock_minimo integer not null default 5,
    estado varchar(20) not null default 'ACTIVO',
    id_categoria integer not null references datacell.categorias(id_categoria) on delete restrict,
    id_marca integer not null references datacell.marcas(id_marca) on delete restrict,
    constraint ck_productos_estado check (estado in ('ACTIVO', 'INACTIVO')),
    constraint ck_productos_precios check (precio_compra >= 0 and precio_venta >= 0),
    constraint ck_productos_stock check (stock >= 0 and stock_minimo >= 0)
);

create table datacell.ventas (
    id_venta integer generated by default as identity primary key,
    fecha timestamptz not null default now(),
    id_cliente integer not null references datacell.clientes(id_cliente) on delete restrict,
    id_usuario integer not null references datacell.usuarios(id_usuario) on delete restrict,
    tipo_comprobante varchar(20) not null default 'BOLETA',
    serie varchar(4) not null,
    numero varchar(8),
    subtotal numeric(12, 2) not null,
    igv numeric(12, 2) not null,
    total numeric(12, 2) not null,
    estado varchar(20) not null default 'REGISTRADA',
    observacion varchar(250),
    constraint uq_ventas_comprobante unique (tipo_comprobante, serie, numero),
    constraint ck_ventas_tipo_comprobante check (tipo_comprobante in ('BOLETA', 'FACTURA')),
    constraint ck_ventas_estado check (estado in ('REGISTRADA', 'ANULADA')),
    constraint ck_ventas_totales check (subtotal >= 0 and igv >= 0 and total >= 0)
);

create table datacell.detalles_venta (
    id_detalle_venta integer generated by default as identity primary key,
    id_venta integer not null references datacell.ventas(id_venta) on delete cascade,
    id_producto integer not null references datacell.productos(id_producto) on delete restrict,
    cantidad integer not null,
    precio_unitario numeric(12, 2) not null,
    constraint uq_detalles_venta_producto unique (id_venta, id_producto),
    constraint ck_detalles_venta_cantidad check (cantidad > 0),
    constraint ck_detalles_venta_precio check (precio_unitario >= 0)
);

create table datacell.pagos (
    id_pago integer generated by default as identity primary key,
    id_venta integer not null references datacell.ventas(id_venta) on delete cascade,
    fecha timestamptz not null default now(),
    metodo varchar(20) not null,
    estado varchar(20) not null default 'PAGADO',
    monto numeric(12, 2) not null,
    referencia varchar(80),
    constraint ck_pagos_metodo check (metodo in ('EFECTIVO', 'TARJETA', 'YAPE', 'TRANSFERENCIA')),
    constraint ck_pagos_estado check (estado in ('PENDIENTE', 'PAGADO', 'OBSERVADO', 'ANULADO')),
    constraint ck_pagos_monto check (monto > 0)
);

create table datacell.reclamos_cliente (
    id_reclamo integer generated by default as identity primary key,
    fecha timestamptz not null default now(),
    id_cliente integer not null references datacell.clientes(id_cliente) on delete restrict,
    id_venta integer references datacell.ventas(id_venta) on delete set null,
    id_producto integer references datacell.productos(id_producto) on delete set null,
    motivo varchar(120) not null,
    descripcion varchar(500) not null,
    canal varchar(30) not null default 'PRESENCIAL',
    prioridad varchar(10) not null default 'MEDIA',
    estado varchar(20) not null default 'REGISTRADO',
    id_usuario integer not null references datacell.usuarios(id_usuario) on delete restrict,
    observacion varchar(250),
    constraint ck_reclamos_prioridad check (prioridad in ('BAJA', 'MEDIA', 'ALTA')),
    constraint ck_reclamos_estado check (estado in ('REGISTRADO', 'EN_REVISION', 'ATENDIDO', 'CERRADO'))
);

create table datacell.solicitudes_compra (
    id_solicitud_compra integer generated by default as identity primary key,
    numero varchar(20) unique,
    fecha timestamptz not null default now(),
    fecha_requerida date,
    id_proveedor integer references datacell.proveedores(id_proveedor) on delete restrict,
    id_usuario integer not null references datacell.usuarios(id_usuario) on delete restrict,
    prioridad varchar(10) not null default 'MEDIA',
    estado varchar(20) not null default 'PENDIENTE',
    total_estimado numeric(12, 2) not null default 0,
    observacion varchar(500),
    constraint ck_solicitudes_compra_prioridad check (prioridad in ('BAJA', 'MEDIA', 'ALTA')),
    constraint ck_solicitudes_compra_estado check (estado in ('PENDIENTE', 'APROBADA', 'RECHAZADA', 'ATENDIDA')),
    constraint ck_solicitudes_compra_total check (total_estimado >= 0)
);

create table datacell.detalles_solicitud_compra (
    id_detalle_solicitud integer generated by default as identity primary key,
    id_solicitud_compra integer not null references datacell.solicitudes_compra(id_solicitud_compra) on delete cascade,
    id_producto integer not null references datacell.productos(id_producto) on delete restrict,
    cantidad integer not null,
    constraint uq_detalles_solicitud_compra_producto unique (id_solicitud_compra, id_producto),
    constraint ck_detalles_solicitud_compra_cantidad check (cantidad > 0)
);

create table datacell.solicitudes_cotizacion (
    id_solicitud_cotizacion integer generated by default as identity primary key,
    numero varchar(20) unique,
    fecha timestamptz not null default now(),
    fecha_limite date,
    id_usuario integer not null references datacell.usuarios(id_usuario) on delete restrict,
    estado varchar(20) not null default 'PENDIENTE',
    observacion varchar(500),
    constraint ck_solicitudes_cotizacion_estado check (estado in ('PENDIENTE', 'RESPONDIDA', 'CANCELADA'))
);

create table datacell.detalles_solicitud_cotizacion (
    id_detalle_cotizacion integer generated by default as identity primary key,
    id_solicitud_cotizacion integer not null references datacell.solicitudes_cotizacion(id_solicitud_cotizacion) on delete cascade,
    id_producto integer not null references datacell.productos(id_producto) on delete restrict,
    cantidad integer not null,
    precio_unitario numeric(12, 2),
    constraint uq_detalles_solicitud_cotizacion_producto unique (id_solicitud_cotizacion, id_producto),
    constraint ck_detalles_solicitud_cotizacion_cantidad check (cantidad > 0)
);

create table datacell.solicitudes_cotizacion_proveedores (
    id_solicitud_cotizacion integer not null references datacell.solicitudes_cotizacion(id_solicitud_cotizacion) on delete cascade,
    id_proveedor integer not null references datacell.proveedores(id_proveedor) on delete restrict,
    fecha_respuesta timestamptz,
    estado varchar(20) not null default 'PENDIENTE',
    primary key (id_solicitud_cotizacion, id_proveedor),
    constraint ck_cotizacion_proveedor_estado check (estado in ('PENDIENTE', 'RESPONDIDA', 'DESCARTADA'))
);

create table datacell.compras (
    id_compra integer generated by default as identity primary key,
    numero varchar(20) unique,
    fecha timestamptz not null default now(),
    id_proveedor integer not null references datacell.proveedores(id_proveedor) on delete restrict,
    id_usuario integer not null references datacell.usuarios(id_usuario) on delete restrict,
    id_solicitud_compra integer references datacell.solicitudes_compra(id_solicitud_compra) on delete set null,
    subtotal numeric(12, 2) not null default 0,
    igv numeric(12, 2) not null default 0,
    total numeric(12, 2) not null default 0,
    estado varchar(20) not null default 'PENDIENTE',
    observacion varchar(500),
    constraint ck_compras_estado check (estado in ('PENDIENTE', 'PARCIAL', 'RECIBIDA', 'ANULADA')),
    constraint ck_compras_totales check (subtotal >= 0 and igv >= 0 and total >= 0)
);

create table datacell.detalles_compra (
    id_detalle_compra integer generated by default as identity primary key,
    id_compra integer not null references datacell.compras(id_compra) on delete cascade,
    id_producto integer not null references datacell.productos(id_producto) on delete restrict,
    cantidad integer not null,
    precio_compra numeric(12, 2) not null,
    constraint uq_detalles_compra_producto unique (id_compra, id_producto),
    constraint ck_detalles_compra_cantidad check (cantidad > 0),
    constraint ck_detalles_compra_precio check (precio_compra >= 0)
);

create table datacell.recepciones (
    id_recepcion integer generated by default as identity primary key,
    numero varchar(20) unique,
    fecha timestamptz not null default now(),
    id_compra integer not null references datacell.compras(id_compra) on delete restrict,
    id_usuario integer not null references datacell.usuarios(id_usuario) on delete restrict,
    guia varchar(50),
    observacion varchar(500)
);

create table datacell.detalles_recepcion (
    id_detalle_recepcion integer generated by default as identity primary key,
    id_recepcion integer not null references datacell.recepciones(id_recepcion) on delete cascade,
    id_producto integer not null references datacell.productos(id_producto) on delete restrict,
    cantidad integer not null,
    constraint uq_detalles_recepcion_producto unique (id_recepcion, id_producto),
    constraint ck_detalles_recepcion_cantidad check (cantidad > 0)
);

create table datacell.movimientos_inventario (
    id_movimiento integer generated by default as identity primary key,
    fecha timestamptz not null default now(),
    id_producto integer not null references datacell.productos(id_producto) on delete restrict,
    tipo_movimiento varchar(30) not null,
    cantidad integer not null,
    stock_anterior integer not null,
    stock_nuevo integer not null,
    id_venta integer references datacell.ventas(id_venta) on delete set null,
    id_recepcion integer references datacell.recepciones(id_recepcion) on delete set null,
    observacion varchar(500),
    id_usuario integer not null references datacell.usuarios(id_usuario) on delete restrict,
    constraint ck_movimientos_tipo check (tipo_movimiento in ('COMPRA', 'VENTA', 'AJUSTE', 'DEVOLUCION_COMPRA', 'DEVOLUCION_VENTA')),
    constraint ck_movimientos_stock check (cantidad > 0 and stock_anterior >= 0 and stock_nuevo >= 0)
);

-- Indices de busqueda, claves foraneas y reportes frecuentes.
create index ix_usuarios_id_rol on datacell.usuarios(id_rol);
create index ix_clientes_nombres on datacell.clientes(nombres);
create index ix_proveedores_razon_social on datacell.proveedores(razon_social);
create index ix_productos_nombre on datacell.productos(nombre);
create index ix_productos_id_categoria on datacell.productos(id_categoria);
create index ix_productos_id_marca on datacell.productos(id_marca);
create index ix_ventas_fecha on datacell.ventas(fecha);
create index ix_ventas_id_cliente on datacell.ventas(id_cliente);
create index ix_ventas_id_usuario on datacell.ventas(id_usuario);
create index ix_detalles_venta_id_producto on datacell.detalles_venta(id_producto);
create index ix_pagos_id_venta on datacell.pagos(id_venta);
create index ix_pagos_fecha_estado on datacell.pagos(fecha, estado);
create index ix_reclamos_cliente_fecha on datacell.reclamos_cliente(id_cliente, fecha);
create index ix_reclamos_id_venta on datacell.reclamos_cliente(id_venta);
create index ix_reclamos_id_producto on datacell.reclamos_cliente(id_producto);
create index ix_reclamos_id_usuario on datacell.reclamos_cliente(id_usuario);
create index ix_solicitudes_compra_estado_fecha on datacell.solicitudes_compra(estado, fecha);
create index ix_solicitudes_compra_id_proveedor on datacell.solicitudes_compra(id_proveedor);
create index ix_solicitudes_compra_id_usuario on datacell.solicitudes_compra(id_usuario);
create index ix_detalles_solicitud_compra_id_producto on datacell.detalles_solicitud_compra(id_producto);
create index ix_solicitudes_cotizacion_estado_fecha on datacell.solicitudes_cotizacion(estado, fecha);
create index ix_solicitudes_cotizacion_id_usuario on datacell.solicitudes_cotizacion(id_usuario);
create index ix_detalles_cotizacion_id_producto on datacell.detalles_solicitud_cotizacion(id_producto);
create index ix_cotizacion_proveedor_id_proveedor on datacell.solicitudes_cotizacion_proveedores(id_proveedor);
create index ix_compras_estado_fecha on datacell.compras(estado, fecha);
create index ix_compras_id_proveedor on datacell.compras(id_proveedor);
create index ix_compras_id_usuario on datacell.compras(id_usuario);
create index ix_compras_id_solicitud on datacell.compras(id_solicitud_compra);
create index ix_detalles_compra_id_producto on datacell.detalles_compra(id_producto);
create index ix_recepciones_compra_fecha on datacell.recepciones(id_compra, fecha);
create index ix_recepciones_id_usuario on datacell.recepciones(id_usuario);
create index ix_detalles_recepcion_id_producto on datacell.detalles_recepcion(id_producto);
create index ix_movimientos_producto_fecha on datacell.movimientos_inventario(id_producto, fecha);
create index ix_movimientos_id_venta on datacell.movimientos_inventario(id_venta);
create index ix_movimientos_id_recepcion on datacell.movimientos_inventario(id_recepcion);
create index ix_movimientos_id_usuario on datacell.movimientos_inventario(id_usuario);

-- Defensa en profundidad. El esquema no se expone al Data API y no concede acceso a anon/authenticated.
alter table datacell.roles enable row level security;
alter table datacell.usuarios enable row level security;
alter table datacell.clientes enable row level security;
alter table datacell.proveedores enable row level security;
alter table datacell.categorias enable row level security;
alter table datacell.marcas enable row level security;
alter table datacell.productos enable row level security;
alter table datacell.ventas enable row level security;
alter table datacell.detalles_venta enable row level security;
alter table datacell.pagos enable row level security;
alter table datacell.reclamos_cliente enable row level security;
alter table datacell.solicitudes_compra enable row level security;
alter table datacell.detalles_solicitud_compra enable row level security;
alter table datacell.solicitudes_cotizacion enable row level security;
alter table datacell.detalles_solicitud_cotizacion enable row level security;
alter table datacell.solicitudes_cotizacion_proveedores enable row level security;
alter table datacell.compras enable row level security;
alter table datacell.detalles_compra enable row level security;
alter table datacell.recepciones enable row level security;
alter table datacell.detalles_recepcion enable row level security;
alter table datacell.movimientos_inventario enable row level security;

-- Catalogos y usuarios de demostracion. Las contrasenas usan PasswordHasher de ASP.NET Core.
insert into datacell.roles(nombre) values
    ('ADMINISTRADOR'), ('CAJERO'), ('ALMACEN'), ('ASISTENTE_COMPRAS');

insert into datacell.usuarios(nombres, apellidos, correo, password_hash, id_rol) values
    ('Daniel Francisco', 'Aguirre Espinoza', 'daniel@datacell.local', 'AQAAAAIAAYagAAAAEIel4/SYKW0NrL6ZmYfG3Lwa1gUKt6V1nKrMIyHCpCkNNEfrobUm6/d3c+zLSa1ptw==', (select id_rol from datacell.roles where nombre = 'ADMINISTRADOR')),
    ('Joel Alexander', 'Diaz Gutierrez', 'joel@datacell.local', 'AQAAAAIAAYagAAAAEMm2LwZ//XZ0Xquxy8vq6XJPNxEtJViotLDJAzk5QDMZ08U/zUDhgNZ99CE70miVMQ==', (select id_rol from datacell.roles where nombre = 'ASISTENTE_COMPRAS')),
    ('Luis Fabricio', 'Durand Durand', 'luis@datacell.local', 'AQAAAAIAAYagAAAAEH/3H1c6s/wDOxAxvjdNbEqeEzJUC3Imk7o/4nkI0sIS/BPEUVXPrtqhOxglYbf8zQ==', (select id_rol from datacell.roles where nombre = 'ALMACEN')),
    ('Stefano Jose', 'Gomez Medina', 'stefano@datacell.local', 'AQAAAAIAAYagAAAAEDM/q/yhBAkN61xVj2VwlyMozU8rjeYcUPIjLiLnWzb5Fn/yLIFN9b5iqh5MdZTZgQ==', (select id_rol from datacell.roles where nombre = 'CAJERO')),
    ('Gerardo Favian', 'Palacios Bazan', 'gerardo@datacell.local', 'AQAAAAIAAYagAAAAEIwdr19S1Ju6LIGhDm3q6f7ud3YweGLnXpnVcz+dcpZzjjTdA27jvf1D2zmlly6foQ==', (select id_rol from datacell.roles where nombre = 'ADMINISTRADOR'));

insert into datacell.categorias(nombre) values
    ('Protectores'), ('Cargadores'), ('Audio'), ('Energia'), ('Cables');
insert into datacell.marcas(nombre) values ('Apple'), ('Samsung'), ('Generico');

insert into datacell.productos(codigo, codigo_barras, nombre, descripcion, precio_compra, precio_venta, stock, stock_minimo, id_categoria, id_marca) values
    ('PROD-001', null, 'Funda iPhone 14', 'Funda protectora de silicona', 14, 25, 120, 15, (select id_categoria from datacell.categorias where nombre = 'Protectores'), (select id_marca from datacell.marcas where nombre = 'Apple')),
    ('PROD-002', null, 'Cargador USB-C 20W', 'Cargador rapido para carga diaria', 18, 30, 85, 10, (select id_categoria from datacell.categorias where nombre = 'Cargadores'), (select id_marca from datacell.marcas where nombre = 'Generico')),
    ('PROD-003', null, 'Audifonos Bluetooth', 'Audifonos inalambricos', 28, 45, 60, 8, (select id_categoria from datacell.categorias where nombre = 'Audio'), (select id_marca from datacell.marcas where nombre = 'Generico')),
    ('PROD-004', null, 'Mica templada 9H', 'Mica de vidrio templado', 5, 12, 150, 20, (select id_categoria from datacell.categorias where nombre = 'Protectores'), (select id_marca from datacell.marcas where nombre = 'Samsung')),
    ('PROD-005', null, 'Power Bank 10000mAh', 'Bateria portatil', 45, 65, 7, 10, (select id_categoria from datacell.categorias where nombre = 'Energia'), (select id_marca from datacell.marcas where nombre = 'Generico')),
    ('PROD-006', null, 'Cable Lightning 1m', 'Cable de carga Lightning', 8, 15, 200, 25, (select id_categoria from datacell.categorias where nombre = 'Cables'), (select id_marca from datacell.marcas where nombre = 'Apple')),
    -- El SQL MySQL heredado reutilizaba PROD-001/002 para articulos distintos al catalogo de la app.
    -- Se preservan sus filas y codigos de barras con un codigo tecnico sin colision.
    ('MYSQL-PROD-001', '7750001000012', 'Cargador USB-C 25W', 'Cargador rapido compatible', 35, 59.90, 20, 5, (select id_categoria from datacell.categorias where nombre = 'Cargadores'), (select id_marca from datacell.marcas where nombre = 'Generico')),
    ('MYSQL-PROD-002', '7750001000029', 'Mica templada Galaxy A55', 'Protector de pantalla', 5, 14.90, 8, 10, (select id_categoria from datacell.categorias where nombre = 'Protectores'), (select id_marca from datacell.marcas where nombre = 'Samsung'));

insert into datacell.clientes(nombres, apellidos, documento, direccion, telefono, correo) values
    ('Maria', 'Torres', '45678912', null, '987654321', 'maria.torres@mail.com'),
    ('Luis', 'Herrera', '71234567', null, '976543210', 'luis.herrera@mail.com'),
    ('Camila', 'Rojas', '70011223', null, '965432109', 'camila.rojas@mail.com'),
    ('Jorge', 'Salas', '43098765', null, '954321098', 'jorge.salas@mail.com'),
    ('Cliente', 'Demo', '00000001', 'Lima', '900000001', 'cliente@datacell.local');

insert into datacell.proveedores(ruc, razon_social, direccion, contacto, telefono, correo) values
    ('20123456789', 'Tecnologia Peru S.A.C.', null, 'Rosa Medina', '014478899', 'ventas@tecnologiaperu.com'),
    ('20555111222', 'CompuSolutions S.A.C.', null, 'Carlos Paredes', '016632211', 'contacto@compusolutions.com'),
    ('20666777888', 'Importaciones Movil E.I.R.L.', null, 'Lucia Vargas', '017771122', 'logistica@importmovil.com'),
    -- El RUC original ya pertenecia a Tecnologia Peru en los datos operativos; se remapea y documenta.
    ('20999999991', 'Proveedor Demo SAC', 'Av. Tecnologia 123, Lima', 'Contacto Demo', '900000002', 'proveedor@datacell.local');

insert into datacell.ventas(fecha, id_cliente, id_usuario, tipo_comprobante, serie, numero, subtotal, igv, total) values
    (now(), (select id_cliente from datacell.clientes where documento = '45678912'), (select id_usuario from datacell.usuarios where correo = 'stefano@datacell.local'), 'BOLETA', 'B001', '00000124', 76.19, 13.71, 89.90),
    (now(), (select id_cliente from datacell.clientes where documento = '71234567'), (select id_usuario from datacell.usuarios where correo = 'stefano@datacell.local'), 'FACTURA', 'F001', '00000088', 122.88, 22.12, 145.00),
    (now() - interval '1 day', (select id_cliente from datacell.clientes where documento = '70011223'), (select id_usuario from datacell.usuarios where correo = 'stefano@datacell.local'), 'BOLETA', 'B001', '00000122', 55.08, 9.92, 65.00),
    (now() - interval '1 day', (select id_cliente from datacell.clientes where documento = '43098765'), (select id_usuario from datacell.usuarios where correo = 'stefano@datacell.local'), 'BOLETA', 'B001', '00000118', 101.69, 18.31, 120.00);

insert into datacell.pagos(id_venta, fecha, metodo, estado, monto) values
    ((select id_venta from datacell.ventas where serie = 'B001' and numero = '00000124'), now(), 'YAPE', 'PAGADO', 89.90),
    ((select id_venta from datacell.ventas where serie = 'F001' and numero = '00000088'), now(), 'TARJETA', 'PAGADO', 145.00),
    ((select id_venta from datacell.ventas where serie = 'B001' and numero = '00000122'), now() - interval '1 day', 'EFECTIVO', 'OBSERVADO', 65.00),
    ((select id_venta from datacell.ventas where serie = 'B001' and numero = '00000118'), now() - interval '1 day', 'TRANSFERENCIA', 'PAGADO', 120.00);

insert into datacell.reclamos_cliente(fecha, id_cliente, motivo, descripcion, canal, prioridad, id_usuario) values
    (now() - interval '2 days', (select id_cliente from datacell.clientes where documento = '70011223'), 'Producto defectuoso', 'Reclamo de demostracion para seguimiento.', 'PRESENCIAL', 'MEDIA', (select id_usuario from datacell.usuarios where correo = 'stefano@datacell.local')),
    (now() - interval '4 days', (select id_cliente from datacell.clientes where documento = '45678912'), 'Cambio solicitado', 'Reclamo de demostracion para seguimiento.', 'PRESENCIAL', 'MEDIA', (select id_usuario from datacell.usuarios where correo = 'stefano@datacell.local')),
    (now() - interval '6 days', (select id_cliente from datacell.clientes where documento = '71234567'), 'Atencion recibida', 'Reclamo de demostracion para seguimiento.', 'PRESENCIAL', 'MEDIA', (select id_usuario from datacell.usuarios where correo = 'stefano@datacell.local'));

insert into datacell.solicitudes_compra(numero, fecha, id_proveedor, id_usuario, estado, total_estimado) values
    ('SC-2026-0007', now(), (select id_proveedor from datacell.proveedores where ruc = '20123456789'), (select id_usuario from datacell.usuarios where correo = 'joel@datacell.local'), 'PENDIENTE', 680),
    ('SC-2026-0006', now() - interval '2 days', (select id_proveedor from datacell.proveedores where ruc = '20555111222'), (select id_usuario from datacell.usuarios where correo = 'daniel@datacell.local'), 'APROBADA', 1240),
    ('SC-2026-0005', now() - interval '5 days', (select id_proveedor from datacell.proveedores where ruc = '20666777888'), (select id_usuario from datacell.usuarios where correo = 'luis@datacell.local'), 'ATENDIDA', 920);

insert into datacell.detalles_solicitud_compra(id_solicitud_compra, id_producto, cantidad) values
    ((select id_solicitud_compra from datacell.solicitudes_compra where numero = 'SC-2026-0007'), (select id_producto from datacell.productos where codigo = 'PROD-005'), 20),
    ((select id_solicitud_compra from datacell.solicitudes_compra where numero = 'SC-2026-0006'), (select id_producto from datacell.productos where codigo = 'PROD-002'), 20),
    ((select id_solicitud_compra from datacell.solicitudes_compra where numero = 'SC-2026-0005'), (select id_producto from datacell.productos where codigo = 'PROD-003'), 20);

insert into datacell.compras(numero, fecha, id_proveedor, id_usuario, id_solicitud_compra, subtotal, igv, total) values
    ('OC-2026-0006', now() - interval '2 days', (select id_proveedor from datacell.proveedores where ruc = '20555111222'), (select id_usuario from datacell.usuarios where correo = 'daniel@datacell.local'), (select id_solicitud_compra from datacell.solicitudes_compra where numero = 'SC-2026-0006'), 5900, 1062, 6962),
    ('OC-2026-0005', now() - interval '5 days', (select id_proveedor from datacell.proveedores where ruc = '20666777888'), (select id_usuario from datacell.usuarios where correo = 'daniel@datacell.local'), (select id_solicitud_compra from datacell.solicitudes_compra where numero = 'SC-2026-0005'), 5900, 1062, 6962);

insert into datacell.detalles_compra(id_compra, id_producto, cantidad, precio_compra)
select compra.id_compra, producto.id_producto, 50, producto.precio_compra
from datacell.compras compra
cross join datacell.productos producto
where compra.numero in ('OC-2026-0005', 'OC-2026-0006')
  and producto.codigo not like 'MYSQL-%';

comment on schema datacell is 'Modelo normalizado de ventas, compras e inventario de DataCell.';
comment on table datacell.pagos is 'Pagos separados de la venta para permitir conciliacion y pagos multiples.';
comment on table datacell.solicitudes_cotizacion_proveedores is 'Relacion muchos-a-muchos entre una cotizacion y sus proveedores destinatarios.';
